### ISSUE TITLE
multiple issues running an instance of voice-web

### ISSUE THREAD

**Issue by rkeiii** [common-voice/common-voice#1534]
Hello,

I have run into some issues trying to deploy my own instance of voice-web. I have defined my own environment "live" which I have configured in a live_server_config.json and in database.json (because I couldn't figure out how to make it work for db migration runs without configuring it in both locations). The problems I'm experiencing are:

1. I get the following error about the fact that the clips table does not exist when starting up the Docker container.
```
{"msg":"Error: Table 'voiceweb.clips' doesn't exist","name":"voice","nickname":"Kamph","level":"error","hostname":"ate","pid":21283,"time":"2018-10-26T21:13:24.911Z","release_version":null}
```

2. I am also unable to run any of the db migrations which I would think might resolve the first problem. Note the live database does get a "migrations" table created but no other schema.
```
rkeiii@ate:~/workspace/voice-web$ yarn run migrate up --all --env live -m /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
yarn run v1.7.0
$ cd server/src/lib/model/db && db-migrate up --all --env live -m /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
(node:21706) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
[INFO] No migrations to run
(node:21706) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
[INFO] Done
Done in 1.63s.
rkeiii@ate:~/workspace/voice-web$ yarn run migrate reset --all --env live -m /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
yarn run v1.7.0
$ cd server/src/lib/model/db && db-migrate reset --all --env live -m /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
(node:21735) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
[INFO] No migrations to run
(node:21735) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
[INFO] Done
Done in 1.20s.
rkeiii@ate:~/workspace/voice-web$ yarn run migrate up --all --env live -m /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
yarn run v1.7.0
$ cd server/src/lib/model/db && db-migrate up --all --env live -m /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
(node:21758) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
[INFO] No migrations to run
(node:21758) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
[INFO] Done
Done in 1.52s.
rkeiii@ate:~/workspace/voice-web$ ls -l /home/rkeiii/workspace/voice-web/server/src/lib/model/db/migrations
total 68
-rw-rw-r-- 1 rkeiii rkeiii 2313 Oct 15 14:53 20171205171637-initialize-db.ts
-rw-rw-r-- 1 rkeiii rkeiii  525 Oct 15 14:53 20180118135749-add-timestamps.ts
-rw-rw-r-- 1 rkeiii rkeiii  441 Oct 15 14:53 20180221154147-add-bucket-to-user_clients-and-sentences.ts
-rw-rw-r-- 1 rkeiii rkeiii  572 Oct 15 14:53 20180309110854-add-requested-languages.ts
-rw-rw-r-- 1 rkeiii rkeiii  418 Oct 15 14:53 20180321161005-add-sessions.ts
-rw-rw-r-- 1 rkeiii rkeiii  556 Oct 15 14:53 20180430130010-locales.ts
-rw-rw-r-- 1 rkeiii rkeiii  547 Oct 15 14:53 20180503112435-user_client-locale-bucket.ts
-rw-rw-r-- 1 rkeiii rkeiii  224 Oct 15 14:53 20180517084308-sentences-text-index.ts
-rw-rw-r-- 1 rkeiii rkeiii  228 Oct 15 14:53 20180518122522-clips-sentence-index.ts
-rw-rw-r-- 1 rkeiii rkeiii  420 Oct 15 14:53 20180528105532-add-cache-columns-to-sentences-and-clips.ts
-rw-rw-r-- 1 rkeiii rkeiii  290 Oct 15 14:53 20180531091919-clips_and_votes-created-at-index.ts
-rw-rw-r-- 1 rkeiii rkeiii  522 Oct 15 14:53 20180602125529-user-client-accents.ts
-rw-rw-r-- 1 rkeiii rkeiii  466 Oct 15 14:53 20180626105114-skipped-sentences.ts
-rw-rw-r-- 1 rkeiii rkeiii  160 Oct 15 14:53 20180629094740-add-basket-token-to-user.ts
-rw-rw-r-- 1 rkeiii rkeiii  623 Oct 15 14:53 20180907112935-user-client-activities.ts
-rw-rw-r-- 1 rkeiii rkeiii  334 Oct 15 14:53 20180910121256-user-sso-fields.ts
-rw-rw-r-- 1 rkeiii rkeiii  312 Oct 15 14:53 20180927134400-user-client-visible-and-skip-submission-feedback.ts
rkeiii@ate:~/workspace/voice-web$ 
```

3. I get some mysterious connection error to port 8500!? I have absolutely no idea what this is about.
```
{"msg":"uncaught exception, Error: session create: connect ECONNREFUSED 127.0.0.1:8500","name":"voice","nickname":"Lichak","level":"error","hostname":"ate","pid":21042,"time":"2018-10-26T21:10:17.273Z","release_version":null}
```

**Comment by kdavis-mozilla** [comment]
@Gregoor when your back can you help with this?

**Comment by Gregoor** [comment]
Hi @rkeiii, the file should be just named `config.json` without the prefix. Also changes to the `database.json` shouldn't be necessary. If the error still occurs after the name change, could you also paste the contents of those files?

**Comment by rkeiii** [comment]
@Gregoor Per your advice I moved the configuration into config.json. I now get significantly more log activity but I still see the same complain about the clips table does not exist. Here's the log output I get...

```
[2018-11-07T14:51:58-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) yarn run v1.9.4
[2018-11-07T14:51:58-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) $ node scripts/dev-server.js
[2018-11-07T14:52:03-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) Rebuilding the server...
[2018-11-07T14:52:04-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) Rebuilding the client...
[2018-11-07T14:52:04-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) (node:27) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[2018-11-07T14:53:41-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) Server built!
[2018-11-07T14:53:57-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) Client built!
[2018-11-07T14:54:00-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) No Auth0 configuration found
[2018-11-07T14:54:01-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "log", "msg": "APPLICATION --, starting", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:01.030Z" }
[2018-11-07T14:54:11-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "error", "msg": "could not connect to db, Error: connect ETIMEDOUT", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:11.040Z" }
[2018-11-07T14:54:11-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "log", "msg": "APPLICATION --, warming up caches", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:11.044Z" }
[2018-11-07T14:54:11-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "log", "msg": "APPLICATION --, listening at http://localhost:9000", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:11.048Z" }
[2018-11-07T14:54:11-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "error", "msg": "Error: connect ETIMEDOUT", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:11.056Z" }
[2018-11-07T14:54:11-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "error", "msg": "uncaught exception, Error: session create: connect ECONNREFUSED 127.0.0.1:8500", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:11.057Z" }
[2018-11-07T14:54:45-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) yarn run v1.9.4
[2018-11-07T14:54:45-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) $ node scripts/dev-server.js
[2018-11-07T14:54:11-08:00] (ecs/CommonVoiceWebappTask-live/9b85d5c3-85c5-44ff-8d29-a1d1f6ff03de) { "hostname": "dc26d47b03ab", "level": "error", "msg": "uncaught exception, Error: session create: connect ECONNREFUSED 127.0.0.1:8500", "name": "voice", "nickname": "Poppert", "pid": 39, "release_version": null, "time": "2018-11-07T22:54:11.057Z" }
[2018-11-07T14:54:49-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) Rebuilding the server...
[2018-11-07T14:54:50-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) Rebuilding the client...
[2018-11-07T14:54:50-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) (node:27) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[2018-11-07T14:56:29-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) Server built!
[2018-11-07T14:56:44-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) No Auth0 configuration found
[2018-11-07T14:56:45-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "log", "msg": "APPLICATION --, starting", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:45.615Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) Client built!
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "error", "msg": "Error: Table 'voiceweb.clips' doesn't exist", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.120Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "log", "msg": "APPLICATION --, warming up caches", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.210Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "log", "msg": "APPLICATION --, listening at http://localhost:9000", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.216Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "error", "msg": "(node:39) UnhandledPromiseRejectionWarning: Error: Table 'voiceweb.clips' doesn't exist\n    at PromisePool.query (webpack:///../node_modules/mysql2/promise.js?:344:20)\n    at Mysql.eval (webpack:///./src/lib/model/db/mysql.ts?:128:76)\n    at step (webpack:///./src/lib/model/db/mysql.ts?:32:23)\n    at Object.eval [as next] (webpack:///./src/lib/model/db/mysql.ts?:13:53)\n    at fulfilled (webpack:///./src/lib/model/db/mysql.ts?:4:58)\n    at \u003canonymous\u003e\n    at process._tickDomainCallback (internal/process/next_tick.js:229:7)", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.313Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "error", "msg": "(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.313Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "error", "msg": "(node:39) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.313Z" }
[2018-11-07T14:56:46-08:00] (ecs/CommonVoiceWebappTask-live/03d91ee2-3c47-4db6-a0ec-c9ca86060957) { "hostname": "a436801f7a06", "level": "error", "msg": "uncaught exception, Error: session create: connect ECONNREFUSED 127.0.0.1:8500", "name": "voice", "nickname": "Walth", "pid": 39, "release_version": null, "time": "2018-11-07T22:56:46.320Z" }
```

**Comment by Gregoor** [comment]
I don't see anything wrong with that config. Regarding migrations: they're automatically run when the server starts up.
My intuition for that error message that says either the db service is not running, not reachable (due to some firewall / other security settings) or the host/part configs are off.

**Comment by rkeiii** [comment]
@Gregoor 

Could you possibly tell me what Common Voice would be trying to connect to on TCP port 8500? I am seeing error output like the following when I startup the application.
```
[2019-02-06T10:59:17-08:00] (ecs/CommonVoiceWebappTask-live/a7d599fb-c71b-48a2-ad8c-ca7a7c0446d7) { "hostname": "8840dcb659a2", "level": "error", "msg": "uncaught exception, Error: session create: connect ECONNREFUSED 127.0.0.1:8500", "name": "voice", "nickname": "Jagielski", "pid": 40, "release_version": null, "time": "2019-02-06T18:59:17.916Z" }
```

**Comment by rkeiii** [comment]
@Gregoor 

After doing some research it appears that voice-web is looking for some shared key-value store called Consul to be running on port 8500? Do you know if there's anyway for us to disable this dependency?

**Comment by Gregoor** [comment]
@rkeiii can you show me the non-secret parts of your config? consul is only used when the environment isn't set to default.

**Comment by rkeiii** [comment]
@Gregoor 

Per your request here's the config file I'm using...
```
{
  "SERVER_PORT": 9000,
  "DB_ROOT_USER": "REDACTED",
  "DB_ROOT_PASS": "REDACTED",
  "MYSQLUSER": "REDACTED",
  "MYSQLPASS": "REDACTED",
  "MYSQLDBNAME": "REDACTED",
  "MYSQLHOST": "REDACTED",
  "MYSQLPORT": 3306,
  "BUCKET_NAME": "REDACTED",
  "BUCKET_LOCATION": "us-east-1",
  "ENVIRONMENT": "default",
  "S3_CONFIG": "S3.Types.ClientConfiguration",
  "ADMIN_EMAILS": "REDACTED",
  "IMPORT_SENTENCES": false,
  "PROD": true
}
```

So I have some good news. After your last reply I tried changing the environment name in my config from "live" to "default" and the application started successfully.

Now I am seeing a new error if I click on the login link (bit the application does load!)...
```
19-02-08T13:11:57-08:00] (ecs/CommonVoiceWebappTask-live/72d2ad21-c413-4701-b649-28ccfe0a21f5) [BE] {"msg":"Error setting user bucket, Error: Column 'client_id' cannot be null","name":"voice","nickname":"Hadwin","level":"error","hostname":"84120cecc641","pid":111,"time":"2019-02-08T21:11:57.618Z","release_version":null}
[2019-02-08T13:25:27-08:00] (ecs/CommonVoiceWebappTask-live/72d2ad21-c413-4701-b649-28ccfe0a21f5) [BE] {"msg":"next is not a function, TypeError: next is not a function\n    at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:186:32)\n    at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:362:7)\n    at router.get (/code/server/src/auth-router.ts:132:12)\n    at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)\n    at next (/code/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)\n    at /code/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)\n    at next (/code/node_modules/express/lib/router/index.js:275:10)\n    at SessionStrategy.strategy.pass (/code/node_modules/passport/lib/middleware/authenticate.js:338:9)\n    at SessionStrategy.authenticate (/code/node_modules/passport/lib/strategies/session.js:75:10)\n    at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:361:16)\n    at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:362:7)\n    at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/code/node_modules/express/lib/router/index.js:317:13)","name":"voice","nickname":"Hadwin","level":"log","hostname":"84120cecc641","pid":111,"time":"2019-02-08T21:25:27.849Z","release_version":null}
[2019-02-08T13:25:27-08:00] (ecs/CommonVoiceWebappTask-live/72d2ad21-c413-4701-b649-28ccfe0a21f5) [BE] {"msg":"/login, next is not a function, TypeError: next is not a function\n    at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:186:32)\n    at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:362:7)\n    at router.get (/code/server/src/auth-router.ts:132:12)\n    at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)\n    at next (/code/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)\n    at /code/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)\n    at next (/code/node_modules/express/lib/router/index.js:275:10)\n    at SessionStrategy.strategy.pass (/code/node_modules/passport/lib/middleware/authenticate.js:338:9)\n    at SessionStrategy.authenticate (/code/node_modules/passport/lib/strategies/session.js:75:10)\n    at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:361:16)\n    at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:362:7)\n    at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)\n    at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9\n    at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/code/node_modules/express/lib/router/index.js:317:13)","name":"voice","nickname":"Hadwin","level":"error","hostname":"84120cecc641","pid":111,"time":"2019-02-08T21:25:27.849Z","release_version":null}
```

**Comment by rkeiii** [comment]
@Gregoor 

Hi Gregor, I'm now able to get speech stored in S3 as MP3 files (which is great!) but I'm still seeing an error and the application crashes after a successful upload. Any ideas what might be happening here?

```
[2019-02-19T16:31:55-05:00] (ecs/CommonVoiceWebappTask-live/90d35513-f7cc-4163-8e8f-75706dc68028) [BE] {"msg":"file written to s3, e3041265-a6ae-4f6f-833d-c6d38d2228ef/6d419f05521a0378fdea5d785759fb87a4d2beb568c830a36e1e70862018171e.mp3","name":"voice","nickname":"Reinartz","level":"log","hostname":"f5b04fc975f6","pid":110,"time":"2019-02-19T21:31:55.800Z","release_version":null}
[2019-02-19T16:31:55-05:00] (ecs/CommonVoiceWebappTask-live/90d35513-f7cc-4163-8e8f-75706dc68028) [BE] {"msg":"error saving clip, Error: Duplicate entry 'e3041265-a6ae-4f6f-833d-c6d38d2228ef-6d419f05521a0378fdea5d78575' for key 'client_sentence_index'","name":"voice","nickname":"Reinartz","level":"error","hostname":"f5b04fc975f6","pid":110,"time":"2019-02-19T21:31:55.815Z","release_version":null}
[2019-02-19T16:31:56-05:00] (ecs/CommonVoiceWebappTask-live/90d35513-f7cc-4163-8e8f-75706dc68028) [BE] {"msg":"file written to s3, e3041265-a6ae-4f6f-833d-c6d38d2228ef/00f4c239a62ce45b78bb0979cb7c9a9834e631aafb77640ff525d2853d6be67b.mp3","name":"voice","nickname":"Reinartz","level":"log","hostname":"f5b04fc975f6","pid":110,"time":"2019-02-19T21:31:56.598Z","release_version":null}
[2019-02-19T16:31:56-05:00] (ecs/CommonVoiceWebappTask-live/90d35513-f7cc-4163-8e8f-75706dc68028) [BE] {"msg":"error saving clip, Error: Duplicate entry 'e3041265-a6ae-4f6f-833d-c6d38d2228ef-00f4c239a62ce45b78bb0979cb7' for key 'client_sentence_index'","name":"voice","nickname":"Reinartz","level":"error","hostname":"f5b04fc975f6","pid":110,"time":"2019-02-19T21:31:56.603Z","release_version":null}
[2019-02-19T16:31:57-05:00] (ecs/CommonVoiceWebappTask-live/90d35513-f7cc-4163-8e8f-75706dc68028) [BE] {"msg":"file written to s3, e3041265-a6ae-4f6f-833d-c6d38d2228ef/6e39990ba6f09fbd48be045bb58ef92cf56b7f65616d5493c3dcbe264ed00a98.mp3","name":"voice","nickname":"Reinartz","level":"log","hostname":"f5b04fc975f6","pid":110,"time":"2019-02-19T21:31:57.675Z","release_version":null}
[2019-02-19T16:31:57-05:00] (ecs/CommonVoiceWebappTask-live/90d35513-f7cc-4163-8e8f-75706dc68028) [BE] {"msg":"error saving clip, Error: Duplicate entry 'e3041265-a6ae-4f6f-833d-c6d38d2228ef-6e39990ba6f09fbd48be045bb58' for key 'client_sentence_index'","name":"voice","nickname":"Reinartz","level":"error","hostname":"f5b04fc975f6","pid":110,"time":"2019-02-19T21:31:57.680Z","release_version":null}
```

**Comment by Gregoor** [comment]
@rkeiii Looks like you're saving a clip that already exists. There's a uniqueness check on sentence + user. Try again with new sentences or new user (private window would do).
