### ISSUE TITLE
Keep getting "Upload of this clip keeps failing" error with local deployment

### ISSUE THREAD

**Issue by jarivk** [common-voice/common-voice#3009]
**Describe the bug**
Have deployed a local server. Able to access the server using localhost:9000 and record the clips. But after I hit submit, the browser keeps showing "Upload of this clip keeps failing" error.

Docker log of web container shows below error.

```
[BE] { NoSuchBucket: The specified bucket does not exist
[BE]     at Request.extractError (/code/node_modules/aws-sdk/lib/services/s3.js:816:35)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:683:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:685:12)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:683:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
[BE]   message: 'The specified bucket does not exist',
[BE]   code: 'NoSuchBucket',
[BE]   region: null,
[BE]   time: 2021-02-09T11:24:46.255Z,
[BE]   requestId: '4442587FB7D0A2F9',
[BE]   extendedRequestId: undefined,
[BE]   cfId: undefined,
[BE]   statusCode: 404,
[BE]   retryable: false,
[BE]   retryDelay: 72.48083382162767 }
```

**To Reproduce**
1. Deploy local server
2. Do 5 recordings 
3. Click submit

**Expected behavior**
Clips should get uploaded and should be seen in s3proxy container.

**Screenshots**

**Desktop or Mobile (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [Chrome]

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**

**Comment by phirework** [comment]
We've made a few updates to the Docker install config recently, please rebuild your images and try with the new configuration. (See [release notes](https://github.com/common-voice/common-voice/releases/tag/release-v1.43.0) if you run into an issue with MySQL versioning). Closing for now.
