### ISSUE TITLE
next is not a function TypeError: next is not a function

### ISSUE THREAD

**Issue by SamuelLarkin** [common-voice/common-voice#3407]
**Describe the bug**
After cloning the repo and running `docker-compose up`, I'm getting the following error message when clicking on `log in` `http://localhost:9000`:

`{"message":""}`

The backend logs:

```
web        | [BE] next is not a function TypeError: next is not a function
web        | [BE]     at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:190:34)
```

**To Reproduce**
```bash
git clone https://github.com/common-voice/common-voice
cd common-voice/
docker-compose up
```
then browse to `http://localhost:9000` then click `log in`.

**Expected behavior**
We should see a login page and not some raw json.

**Desktop or Mobile (please complete the following information):**
 - OS: Windoze 7
 - Browser brave-1.25.72

```
web        | [BE] next is not a function TypeError: next is not a function
web        | [BE]     at attempt (/code/node_modules/passport/lib/middleware/authenticate.js:190:34)
web        | [BE]     at authenticate (/code/node_modules/passport/lib/middleware/authenticate.js:367:7)
web        | [BE]     at /code/server/src/auth-router.ts:190:12
web        | [BE]     at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
web        | [BE]     at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9
web        | [BE]     at handleReturn (/code/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
web        | [BE]     at /code/node_modules/express-promise-router/lib/express-promise-router.js:56:9
web        | [BE]     at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
web        | [BE]     at next (/code/node_modules/express/lib/router/route.js:137:13)
web        | [BE]     at Route.dispatch (/code/node_modules/express/lib/router/route.js:112:3)
web        | [BE]     at Layer.handle [as handle_request] (/code/node_modules/express/lib/router/layer.js:95:5)
web        | [BE]     at /code/node_modules/express/lib/router/index.js:281:22
web        | [BE]     at Function.process_params (/code/node_modules/express/lib/router/index.js:335:12)
web        | [BE]     at next (/code/node_modules/express/lib/router/index.js:275:10)
web        | [BE]     at SessionStrategy.strategy.pass (/code/node_modules/passport/lib/middleware/authenticate.js:343:9)
web        | [BE]     at SessionStrategy.authenticate (/code/node_modules/passport/lib/strategies/session.js:75:10)
```

**Comment by zaccolley** [comment]
Thanks for the issue. I'm curious if this is because we're missing the Auth0 credentials. Did you add them from these instructions? https://github.com/common-voice/common-voice/blob/fef16a92ba054675354b35f9a1ea9ed34ccdc9c6/docs/DEVELOPMENT.md#authentication

If that's the case we should make the error much more clear!

**Comment by SamuelLarkin** [comment]
Indeed, I didn't have auth0.com setup.
Agreed with making the error message clearer.

**Comment by zaccolley** [comment]
Cool, let's leave this issue open so we can make sure we add the better error messaging in.

**Comment by moz-bozden** [comment]
Closing this as stale and not related to the current code-base.
