### ISSUE TITLE
Table 'accents' already exists

### ISSUE THREAD

**Issue by SamuelLarkin** [common-voice/common-voice#3408]
**Describe the bug**
When restarting `docker-compose up` for a second time, the `accents` table is recreated.

**To Reproduce**
```
docker-compose up
CTRL-C
docker-compose up
```

**Expected behavior**
The `accents` table shouldn't not be recreated.

**Desktop or Mobile (please complete the following information):**
 - OS: Windoze 7
 - Browser Brave-1.25.72

**Additional context**
```
web        | [BE] APPLICATION -- Maintenance error OperationalError: ER_TABLE_EXISTS_ERROR: Table 'accents' already exists
web        | [BE]     at Query.Sequence._packetToError (/code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
web        | [BE]     at Query.ErrorPacket (/code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
web        | [BE]     at Protocol._parsePacket (/code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
web        | [BE]     at Parser._parsePacket (/code/node_modules/mysql/lib/protocol/Parser.js:433:10)
web        | [BE]     at Parser.write (/code/node_modules/mysql/lib/protocol/Parser.js:43:10)
web        | [BE]     at Protocol.write (/code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
web        | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:88:28)
web        | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:526:10)
web        | [BE]     at Socket.emit (events.js:314:20)
web        | [BE]     at Socket.EventEmitter.emit (domain.js:483:12)
web        | [BE]     at addChunk (_stream_readable.js:297:12)
web        | [BE]     at readableAddChunk (_stream_readable.js:272:9)
web        | [BE]     at Socket.Readable.push (_stream_readable.js:213:10)
web        | [BE]     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
web        | [BE]     --------------------
web        | [BE]     at Protocol._enqueue (/code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
web        | [BE]     at Connection.query (/code/node_modules/mysql/lib/Connection.js:198:25)
web        | [BE]     at /code/node_modules/db-migrate-mysql/index.js:371:29
web        | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]     at Object.runSql (/code/node_modules/db-migrate-mysql/index.js:366:12)
web        | [BE]     at Class.exports.up (/code/server/src/lib/model/db/migrations/20211110104012-accent-tables-in-db.ts:248:12)
web        | [BE]     at Class.<anonymous> (/code/node_modules/db-migrate/lib/skeleton.js:85:43)
web        | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]     at Class._up (/code/node_modules/db-migrate/lib/skeleton.js:68:12)
web        | [BE]     at Class.up (/code/node_modules/db-migrate/lib/skeleton.js:150:17)
web        | [BE]     at Migrator.up (/code/node_modules/db-migrate/lib/migrator.js:108:14)
web        | [BE]     at /code/node_modules/db-migrate/lib/migrator.js:237:31 {
web        | [BE]   cause: Error: ER_TABLE_EXISTS_ERROR: Table 'accents' already exists
web        | [BE]       at Query.Sequence._packetToError (/code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
web        | [BE]       at Query.ErrorPacket (/code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
web        | [BE]       at Protocol._parsePacket (/code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
web        | [BE]       at Parser._parsePacket (/code/node_modules/mysql/lib/protocol/Parser.js:433:10)
web        | [BE]       at Parser.write (/code/node_modules/mysql/lib/protocol/Parser.js:43:10)
web        | [BE]       at Protocol.write (/code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
web        | [BE]       at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:88:28)
web        | [BE]       at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:526:10)
web        | [BE]       at Socket.emit (events.js:314:20)
web        | [BE]       at Socket.EventEmitter.emit (domain.js:483:12)
web        | [BE]       at addChunk (_stream_readable.js:297:12)
web        | [BE]       at readableAddChunk (_stream_readable.js:272:9)
web        | [BE]       at Socket.Readable.push (_stream_readable.js:213:10)
web        | [BE]       at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
web        | [BE]       --------------------
web        | [BE]       at Protocol._enqueue (/code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
web        | [BE]       at Connection.query (/code/node_modules/mysql/lib/Connection.js:198:25)
web        | [BE]       at /code/node_modules/db-migrate-mysql/index.js:371:29
web        | [BE]       at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]       at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]       at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]       at Object.runSql (/code/node_modules/db-migrate-mysql/index.js:366:12)
web        | [BE]       at Class.exports.up (/code/server/src/lib/model/db/migrations/20211110104012-accent-tables-in-db.ts:248:12)
web        | [BE]       at Class.<anonymous> (/code/node_modules/db-migrate/lib/skeleton.js:85:43)
web        | [BE]       at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]       at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]       at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]       at Class._up (/code/node_modules/db-migrate/lib/skeleton.js:68:12)
web        | [BE]       at Class.up (/code/node_modules/db-migrate/lib/skeleton.js:150:17)
web        | [BE]       at Migrator.up (/code/node_modules/db-migrate/lib/migrator.js:108:14)
web        | [BE]       at /code/node_modules/db-migrate/lib/migrator.js:237:31 {
web        | [BE]     code: 'ER_TABLE_EXISTS_ERROR',
web        | [BE]     errno: 1050,
web        | [BE]     sqlMessage: "Table 'accents' already exists",
web        | [BE]     sqlState: '42S01',
web        | [BE]     index: 0,
web        | [BE]     sql: '\n' +
web        | [BE]       '    CREATE TABLE accents (\n' +
web        | [BE]       '      id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,\n' +
web        | [BE]       '\n' +
web        | [BE]       '      locale_id INT NOT NULL,\n' +
web        | [BE]       '      accent_name VARCHAR(255) CHARSET utf8mb4 NOT NULL,\n' +
web        | [BE]       '      accent_token VARCHAR(255) CHARSET utf8mb4 DEFAULT NULL,\n' +
web        | [BE]       '      user_submitted BOOLEAN DEFAULT FALSE,\n' +
web        | [BE]       '      client_id CHAR(36),\n' +
web        | [BE]       '      approved BOOLEAN DEFAULT FALSE,\n' +
web        | [BE]       '      created_at DATETIME DEFAULT NOW(),\n' +
web        | [BE]       '\n' +
web        | [BE]       '      FOREIGN KEY (client_id) REFERENCES user_clients(client_id) ON DELETE SET NULL,\n' +
web        | [BE]       '      FOREIGN KEY (locale_id) REFERENCES locales(id),\n' +
web        | [BE]       '      UNIQUE KEY accent_key (locale_id, accent_name)\n' +
web        | [BE]       '    )\n' +
web        | [BE]       '    '
web        | [BE]   },
web        | [BE]   isOperational: true,
web        | [BE]   code: 'ER_TABLE_EXISTS_ERROR',
web        | [BE]   errno: 1050,
web        | [BE]   sqlMessage: "Table 'accents' already exists",
web        | [BE]   sqlState: '42S01',
web        | [BE]   index: 0,
web        | [BE]   sql: '\n' +
web        | [BE]     '    CREATE TABLE accents (\n' +
web        | [BE]     '      id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,\n' +
web        | [BE]     '\n' +
web        | [BE]     '      locale_id INT NOT NULL,\n' +
web        | [BE]     '      accent_name VARCHAR(255) CHARSET utf8mb4 NOT NULL,\n' +
web        | [BE]     '      accent_token VARCHAR(255) CHARSET utf8mb4 DEFAULT NULL,\n' +
web        | [BE]     '      user_submitted BOOLEAN DEFAULT FALSE,\n' +
web        | [BE]     '      client_id CHAR(36),\n' +
web        | [BE]     '      approved BOOLEAN DEFAULT FALSE,\n' +
web        | [BE]     '      created_at DATETIME DEFAULT NOW(),\n' +
web        | [BE]     '\n' +
web        | [BE]     '      FOREIGN KEY (client_id) REFERENCES user_clients(client_id) ON DELETE SET NULL,\n' +
web        | [BE]     '      FOREIGN KEY (locale_id) REFERENCES locales(id),\n' +
web        | [BE]     '      UNIQUE KEY accent_key (locale_id, accent_name)\n' +
web        | [BE]     '    )\n' +
web        | [BE]     '    '
web        | [BE] }
```

**Comment by zaccolley** [comment]
Hey @SamuelLarkin I think this is related to this PR comment: https://github.com/common-voice/common-voice/issues/3409#issuecomment-1015334655

Thanks for the issue!

**Comment by Heyhillary** [comment]
Hey @SamuelLarkin ,

Thanks for the request - are you happy with the solution Zac proposed , SO i can close the issue ?

**Comment by zaccolley** [comment]
Great thank you for confirming, will close for now
