### ISSUE TITLE
Error: Table 'voiceweb.skipped_clips' doesn't exist

### ISSUE THREAD

**Issue by SamuelLarkin** [common-voice/common-voice#3409]
**Describe the bug**
Running `docker-compose up`, we are getting the following error `Error: Table 'voiceweb.skipped_clips' doesn't exist`

**To Reproduce**
```
docker-compose up
```

**Expected behavior**
The `voiceweb.skipped` table should exist or be created.

**Desktop or Mobile (please complete the following information):**
 - OS: Windoze 7
 - Browser Brave-1.25.72

**Additional context**
```
web        | [BE] Table 'voiceweb.skipped_clips' doesn't exist Error: Table 'voiceweb.skipped_clips' doesn't exist
web        | [BE]     at PromisePool.query (/code/node_modules/mysql2/promise.js:330:22)
web        | [BE]     at Mysql.query (/code/server/src/lib/model/db/mysql.ts:122:41)
web        | [BE]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
web        | [BE]     at DB.findClipsWithFewVotes (/code/server/src/lib/model/db.ts:364:21)
web        | [BE]     at DB.findClipsNeedingValidation (/code/server/src/lib/model/db.ts:348:11)
web        | [BE]     at Bucket.getRandomClips (/code/server/src/lib/bucket.ts:90:19)
web        | [BE]     at Clip.serveRandomClips (/code/server/src/lib/clip.ts:327:19)
web        | [BE] /api/v1/en/clips?count=10 Table 'voiceweb.skipped_clips' doesn't exist Error: Table 'voiceweb.skipped_clips' doesn't exist
web        | [BE]     at PromisePool.query (/code/node_modules/mysql2/promise.js:330:22)
web        | [BE]     at Mysql.query (/code/server/src/lib/model/db/mysql.ts:122:41)
web        | [BE]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
web        | [BE]     at DB.findClipsWithFewVotes (/code/server/src/lib/model/db.ts:364:21)
web        | [BE]     at DB.findClipsNeedingValidation (/code/server/src/lib/model/db.ts:348:11)
web        | [BE]     at Bucket.getRandomClips (/code/server/src/lib/bucket.ts:90:19)
web        | [BE]     at Clip.serveRandomClips (/code/server/src/lib/clip.ts:327:19)
```

**Comment by zaccolley** [comment]
Hey @SamuelLarkin thanks for your issue. I also ran into this issue recently and I think I've fixed it in a recent PR: #3406

Looks like one of the migration files was breaking.

Could you try dropping the database and rerunning the project:

```
docker-compose up
docker exec -it db bash
> mysql -u root -p
> drop database voiceweb;
```

then stop the process and rerun `docker-compose up`

**Comment by moz-bozden** [comment]
Closing this as stale and not related to the current code-base.
