### ISSUE TITLE
Unable to use S3 Bucket with Common-Voice's `Docker` stack

### ISSUE THREAD

**Issue by SamuelLarkin** [common-voice/common-voice#3701]
**Describe the bug**
Using AWS S3 yields a xml parse error.

**To Reproduce**
Using `docker-compose.yaml` to run the docker stack.
Change `.env-local-docker` from this configuration which works in local mode aka clips are getting recorded to `S3Proxy`
```diff
- CV_S3_CONFIG='{"endpoint": "http://s3proxy:80", "accessKeyId": "local-identity", "secretAccessKey": "local-credential", "s3ForcePathStyle": true}'
+ CV_S3_CONFIG='{"endpoint": "http://ec2-11-111-11-111.ca-central-1.compute.amazonaws.com:80", "accessKeyId": "IIIIIIIIIIIIIIIIIIII", "secretAccessKey": "KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK", "s3ForcePathStyle": true}'
```

**Expected behavior**
Audio clips are save to a AWS S3 Bucket

**Desktop or Mobile (please complete the following information):**
 - OS: docker stack via `docker-compose.yaml`
 - Common-Voice-1.66.0

**Additional context**
`docker container logs web`
```
[BE] /api/v1/str/clips Unexpected close tag
[BE] Line: 6
[BE] Column: 7
[BE] Char: > XMLParserError: Unexpected close tag
[BE] Line: 6
[BE] Column: 7
[BE] Char: >
[BE]     at error (/code/node_modules/sax/lib/sax.js:651:10)
[BE]     at strictFail (/code/node_modules/sax/lib/sax.js:677:7)
[BE]     at closeTag (/code/node_modules/sax/lib/sax.js:871:9)
[BE]     at SAXParser.write (/code/node_modules/sax/lib/sax.js:1436:13)
[BE]     at Parser.exports.Parser.Parser.parseString (/code/node_modules/xml2js/lib/parser.js:322:31)
[BE]     at Parser.parseString (/code/node_modules/xml2js/lib/parser.js:5:59)
[BE]     at NodeXmlParser.parse (/code/node_modules/aws-sdk/lib/xml/node_parser.js:31:10)
[BE]     at Request.extractError (/code/node_modules/aws-sdk/lib/services/s3.js:696:39)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:686:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:688:12)
```

**Comment by SamuelLarkin** [comment]
# `.env-local-docker`
```diff
- CV_S3_CONFIG='{"endpoint": "http://s3proxy:80", "accessKeyId": "local-identity", "secretAccessKey": "local-credential", "s3ForcePathStyle": true}'
+ CV_S3_CONFIG='{"endpoint": "https://s3.amazonaws.com", "accessKeyId": "IIIIIIIIIIIIIIII", "secretAccessKey": "KKKKKKK", "s3ForcePathStyle": true}'
```

# web
```
[BE] All access to this object has been disabled AllAccessDisabled: All access to this object has been disabled
[BE]     at Request.extractError (/code/node_modules/aws-sdk/lib/services/s3.js:710:35)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:686:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:688:12)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:686:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
[BE] /api/v1/str/clips All access to this object has been disabled AllAccessDisabled: All access to this object has been disabled
[BE]     at Request.extractError (/code/node_modules/aws-sdk/lib/services/s3.js:710:35)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:686:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:688:12)
[BE]     at Request.callListeners (/code/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
[BE]     at Request.emit (/code/node_modules/aws-sdk/lib/request.js:686:14)
[BE]     at Request.transition (/code/node_modules/aws-sdk/lib/request.js:22:10)
[BE]     at AcceptorStateMachine.runTo (/code/node_modules/aws-sdk/lib/state_machine.js:14:12)
[BE]     at /code/node_modules/aws-sdk/lib/state_machine.js:26:10
[BE]     at Request.<anonymous> (/code/node_modules/aws-sdk/lib/request.js:38:9)
```

Feels like I'm not pointing to the proper S3 bucket.

**Comment by SamuelLarkin** [comment]
# SOLUTION

Here's a working example of `.env-local-docker`
```diff
- CV_S3_CONFIG='{"endpoint": "http://s3proxy:80", "accessKeyId": "local-identity", "secretAccessKey": "local-credential", "s3ForcePathStyle": true}'
+ CV_S3_CONFIG='{"endpoint": "https://s3.amazonaws.com", "accessKeyId": "my_access_key_id", "secretAccessKey": "my_secret_access_key", "s3ForcePathStyle": true }'
+ BUCKET_LOCATION="ca-central-1"
+ CV_CLIP_BUCKET_NAME=my_s3_bucket_name
+ CV_DATASET_BUCKET_NAME=my_s3_bucket_name
```
