### ISSUE TITLE
[BUG] migration failed to run during server deployment

### ISSUE THREAD

**Issue by alenpaulvarghese** [common-voice/common-voice#3775]
**Describe the bug**
The migration seems to be failing during the deployment of the server. I checked twice already on multiple days and still face this issue.

**To Reproduce**
1. Clone the repository
2. rename the config 
3. docker-compose up

**Expected behavior**
The server should have started without any error.

Os - Gnu/Linux (Ubuntu) x86_64
Docker version - 20.10.12
Docker compose version - 20.10.12

**Build Log**

```
3:30:50 AM - Starting compilation in watch mode...
web      | [CO] 
web      | [FE] Webpack: Rebuilding...
web      | [CO] 
web      | [CO] 3:30:53 AM - Found 0 errors. Watching for file changes.
web      | [BE] 
web      | [BE] 3:31:04 AM - Found 0 errors. Watching for file changes.
web      | [BE] $ cd .. && node server/js/main.js
web      | [BE] Could not load config.json, using defaults (error message: ENOENT: no such file or directory, open './config.json')
web      | [BE] No Auth0 configuration found
web      | [BE] APPLICATION -- starting
web      | [BE] Cache is redis
db       | 2022-08-10T03:31:06.187592Z 2 [Warning] Following users were specified in CREATE USER IF NOT EXISTS but they already exist. Corresponding entry in binary log used default authentication plugin 'mysql_native_password' to rewrite authentication information(if any) for them: 'voicecommons'@'%'
db       | 
web      | [BE] APPLICATION -- performing Maintenance
web      | [BE] Running migrations
web      | [BE] APPLICATION -- listening at http://localhost:9000
web      | [BE] unhandled promise rejection Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
web      | [BE]     at Query.Sequence._packetToError (/code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
web      | [BE]     at Query.ErrorPacket (/code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
web      | [BE]     at Protocol._parsePacket (/code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
web      | [BE]     at Parser._parsePacket (/code/node_modules/mysql/lib/protocol/Parser.js:433:10)
web      | [BE]     at Parser.write (/code/node_modules/mysql/lib/protocol/Parser.js:43:10)
web      | [BE]     at Protocol.write (/code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
web      | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:88:28)
web      | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:526:10)
web      | [BE]     at Socket.emit (events.js:314:20)
web      | [BE]     at Socket.EventEmitter.emit (domain.js:483:12)
web      | [BE]     at addChunk (_stream_readable.js:297:12)
web      | [BE]     at readableAddChunk (_stream_readable.js:272:9)
web      | [BE]     at Socket.Readable.push (_stream_readable.js:213:10)
web      | [BE]     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
web      | [BE]     --------------------
web      | [BE]     at Protocol._enqueue (/code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
web      | [BE]     at Connection.query (/code/node_modules/mysql/lib/Connection.js:198:25)
web      | [BE]     at /code/node_modules/db-migrate-mysql/index.js:371:29
web      | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web      | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web      | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web      | [BE]     at Object.runSql (/code/node_modules/db-migrate-mysql/index.js:366:12)
web      | [BE]     at /code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:115:10
web      | [BE]     at Array.map (<anonymous>)
web      | [BE]     at Class.exports.up (/code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:114:14) {
web      | [BE]   code: 'ER_BAD_FIELD_ERROR',
web      | [BE]   errno: 1054,
web      | [BE]   sqlMessage: "Unknown column 'undefined' in 'field list'",
web      | [BE]   sqlState: '42S22',
web      | [BE]   index: 0,
web      | [BE]   sql: 'INSERT IGNORE INTO variants (locale_id, variant_token, variant_name) VALUES ( undefined,"cy-northwes","North-Western Welsh")'
web      | [BE] }
web      | [BE] [ERROR] Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
web      | [BE]     at Query.Sequence._packetToError (/code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
web      | [BE]     at Query.ErrorPacket (/code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
web      | [BE]     at Protocol._parsePacket (/code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
web      | [BE]     at Parser._parsePacket (/code/node_modules/mysql/lib/protocol/Parser.js:433:10)
web      | [BE]     at Parser.write (/code/node_modules/mysql/lib/protocol/Parser.js:43:10)
web      | [BE]     at Protocol.write (/code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
web      | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:88:28)
web      | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:526:10)
web      | [BE]     at Socket.emit (events.js:314:20)
web      | [BE]     at Socket.EventEmitter.emit (domain.js:483:12)
web      | [BE]     at addChunk (_stream_readable.js:297:12)
web      | [BE]     at readableAddChunk (_stream_readable.js:272:9)
web      | [BE]     at Socket.Readable.push (_stream_readable.js:213:10)
web      | [BE]     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
web      | [BE]     --------------------
web      | [BE]     at Protocol._enqueue (/code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
web      | [BE]     at Connection.query (/code/node_modules/mysql/lib/Connection.js:198:25)
web      | [BE]     at /code/node_modules/db-migrate-mysql/index.js:371:29
web      | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web      | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web      | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web      | [BE]     at Object.runSql (/code/node_modules/db-migrate-mysql/index.js:366:12)
web      | [BE]     at /code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:115:10
web      | [BE]     at Array.map (<anonymous>)
web      | [BE]     at Class.exports.up (/code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:114:14)
db       | 2022-08-10T03:31:06.313848Z 4 [Note] Aborted connection 4 to db: 'voiceweb' user: 'root' host: '172.18.0.5' (Got an error reading communication packets)
db       | 2022-08-10T03:31:06.313862Z 3 [Note] Aborted connection 3 to db: 'voiceweb' user: 'voicecommons' host: '172.18.0.5' (Got an error reading communication packets)
db       | 2022-08-10T03:31:06.313911Z 2 [Note] Aborted connection 2 to db: 'voiceweb' user: 'root' host: '172.18.0.5' (Got an error reading communication packets)
web      | [BE] error Command failed with exit code 1.
web      | [BE] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web      | [FE] Webpack: Built!
```

**Comment by mozgzh** [comment]
Have you imported all languages? It looks like Welsh isn't found (its locale_id is undefined).

**Comment by alenpaul2001** [comment]
I only followed the readme and didn't followed anything other that.

**Comment by mozgzh** [comment]
So just to confirm, `CV_IMPORT_SENTENCES="true"` was set in .env-local-docker and allowed to finish?

**Comment by alenpaul2001** [comment]
nope I didn't set that environment variable if I recall correctly

**Comment by alenpaul2001** [comment]
I copied the example env file to the actual .env path which contained the above mentioned variable, and I think that will take this into account.

**Comment by alenpaul2001** [comment]
I also have to mention that I deleted the migration which was causing the error, it worked and started importing all the languages.
but it exited with another error which I don't remember now

**Comment by ftyers** [comment]
I'm having the same problem on a clean checkout running the same list of commands (e.g. following the docs.)

I have  `CV_IMPORT_SENTENCES="true"`, and the whole environment is:
```
$ cat .env-local-docker
CV_DB_ROOT_PASS="voicewebroot"
CV_MYSQLHOST="db"
CV_S3_CONFIG='{"endpoint": "http://s3proxy:80", "accessKeyId": "local-identity", "secretAccessKey": "local-credential", "s3ForcePathStyle": true}'
CV_S3_LOCAL_DEVELOPMENT_ENDPOINT="http://localhost:9001"
CV_ENVIRONMENT="local"
CV_PROD="false"
CV_IMPORT_SENTENCES="true"
CV_EMAIL_USERNAME_FROM="commonvoice@mozilla.com"
CV_EMAIL_USERNAME_TO="commonvoice@mozilla.com"
CV_REDIS_URL='redis'
```


The resulting log is:
```
5:03:54 PM - Starting compilation in watch mode...
web        | [BE] 
web        | [FE] Webpack: Rebuilding...
web        | [CO] 
web        | [CO] 5:04:01 PM - Found 0 errors. Watching for file changes.
web        | [BE] 
web        | [BE] 5:04:37 PM - Found 0 errors. Watching for file changes.
web        | [BE] $ cd .. && node server/js/main.js
web        | [BE] Could not load config.json, using defaults (error message: ENOENT: no such file or directory, open './config.json')
web        | [BE] No Auth0 configuration found
web        | [BE] APPLICATION -- starting
web        | [BE] Cache is redis
db         | 2022-09-05T17:04:42.484677Z 2 [Warning] Following users were specified in CREATE USER IF NOT EXISTS but they already exist. Corresponding entry in binary log used default authentication plugin 'mysql_native_password' to rewrite authentication information(if any) for them: 'voicecommons'@'%'
db         | 
web        | [BE] APPLICATION -- performing Maintenance
web        | [BE] Running migrations
web        | [BE] APPLICATION -- listening at http://localhost:9000
web        | [BE] unhandled promise rejection Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
web        | [BE]     at Query.Sequence._packetToError (/code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
web        | [BE]     at Query.ErrorPacket (/code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
web        | [BE]     at Protocol._parsePacket (/code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
web        | [BE]     at Parser._parsePacket (/code/node_modules/mysql/lib/protocol/Parser.js:433:10)
web        | [BE]     at Parser.write (/code/node_modules/mysql/lib/protocol/Parser.js:43:10)
web        | [BE]     at Protocol.write (/code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
web        | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:88:28)
web        | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:526:10)
web        | [BE]     at Socket.emit (events.js:314:20)
web        | [BE]     at Socket.EventEmitter.emit (domain.js:483:12)
web        | [BE]     at addChunk (_stream_readable.js:297:12)
web        | [BE]     at readableAddChunk (_stream_readable.js:272:9)
web        | [BE]     at Socket.Readable.push (_stream_readable.js:213:10)
web        | [BE]     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
web        | [BE]     --------------------
web        | [BE]     at Protocol._enqueue (/code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
web        | [BE]     at Connection.query (/code/node_modules/mysql/lib/Connection.js:198:25)
web        | [BE]     at /code/node_modules/db-migrate-mysql/index.js:371:29
web        | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]     at Object.runSql (/code/node_modules/db-migrate-mysql/index.js:366:12)
web        | [BE]     at /code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:115:10
web        | [BE]     at Array.map (<anonymous>)
web        | [BE]     at Class.exports.up (/code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:114:14) {
web        | [BE]   code: 'ER_BAD_FIELD_ERROR',
web        | [BE]   errno: 1054,
web        | [BE]   sqlMessage: "Unknown column 'undefined' in 'field list'",
web        | [BE]   sqlState: '42S22',
web        | [BE]   index: 0,
web        | [BE]   sql: 'INSERT IGNORE INTO variants (locale_id, variant_token, variant_name) VALUES ( undefined,"cy-northwes","North-Western Welsh")'
web        | [BE] }
web        | [BE] [ERROR] Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
web        | [BE]     at Query.Sequence._packetToError (/code/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
web        | [BE]     at Query.ErrorPacket (/code/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
web        | [BE]     at Protocol._parsePacket (/code/node_modules/mysql/lib/protocol/Protocol.js:291:23)
web        | [BE]     at Parser._parsePacket (/code/node_modules/mysql/lib/protocol/Parser.js:433:10)
web        | [BE]     at Parser.write (/code/node_modules/mysql/lib/protocol/Parser.js:43:10)
web        | [BE]     at Protocol.write (/code/node_modules/mysql/lib/protocol/Protocol.js:38:16)
web        | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:88:28)
web        | [BE]     at Socket.<anonymous> (/code/node_modules/mysql/lib/Connection.js:526:10)
web        | [BE]     at Socket.emit (events.js:314:20)
web        | [BE]     at Socket.EventEmitter.emit (domain.js:483:12)
web        | [BE]     at addChunk (_stream_readable.js:297:12)
web        | [BE]     at readableAddChunk (_stream_readable.js:272:9)
web        | [BE]     at Socket.Readable.push (_stream_readable.js:213:10)
web        | [BE]     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
web        | [BE]     --------------------
web        | [BE]     at Protocol._enqueue (/code/node_modules/mysql/lib/protocol/Protocol.js:144:48)
web        | [BE]     at Connection.query (/code/node_modules/mysql/lib/Connection.js:198:25)
web        | [BE]     at /code/node_modules/db-migrate-mysql/index.js:371:29
web        | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]     at Object.runSql (/code/node_modules/db-migrate-mysql/index.js:366:12)
web        | [BE]     at /code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:115:10
web        | [BE]     at Array.map (<anonymous>)
web        | [BE]     at Class.exports.up (/code/server/src/lib/model/db/migrations/20220222145730-import-variant-data.ts:114:14)
db         | 2022-09-05T17:04:42.823613Z 4 [Note] Aborted connection 4 to db: 'voiceweb' user: 'root' host: '172.18.0.5' (Got an error reading communication packets)
db         | 2022-09-05T17:04:42.823791Z 3 [Note] Aborted connection 3 to db: 'voiceweb' user: 'voicecommons' host: '172.18.0.5' (Got an error reading communication packets)
db         | 2022-09-05T17:04:42.824824Z 2 [Note] Aborted connection 2 to db: 'voiceweb' user: 'root' host: '172.18.0.5' (Got an error reading communication packets)
web        | [BE] error Command failed with exit code 1.
web        | [BE] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
web        | [FE] Webpack: Built!
```

**Comment by rotimi-babalola** [comment]
> I also have to mention that I deleted the migration which was causing the error, it worked and started importing all the languages. but it exited with another error which I don't remember now

Hello, @alenpaul2001 is this the error you were getting?

```
[BE] APPLICATION -- Maintenance error TypeError: Cannot read property 'apply' of undefined
web        | [BE]     at Class.<anonymous> (/code/node_modules/db-migrate/lib/skeleton.js:85:42)
web        | [BE]     at Promise._execute (/code/node_modules/bluebird/js/release/debuggability.js:384:9)
web        | [BE]     at Promise._resolveFromExecutor (/code/node_modules/bluebird/js/release/promise.js:518:18)
web        | [BE]     at new Promise (/code/node_modules/bluebird/js/release/promise.js:103:10)
web        | [BE]     at Class._up (/code/node_modules/db-migrate/lib/skeleton.js:68:12)
web        | [BE]     at Class.up (/code/node_modules/db-migrate/lib/skeleton.js:150:17)
web        | [BE]     at Migrator.up (/code/node_modules/db-migrate/lib/migrator.js:108:14)
web        | [BE]     at /code/node_modules/db-migrate/lib/migrator.js:237:31
web        | [BE]     at tryCatcher (/code/node_modules/bluebird/js/release/util.js:16:23)
web        | [BE]     at Promise._settlePromiseFromHandler (/code/node_modules/bluebird/js/release/promise.js:547:31)
web        | [BE]     at Promise._settlePromise (/code/node_modules/bluebird/js/release/promise.js:604:18)
web        | [BE]     at Promise._settlePromise0 (/code/node_modules/bluebird/js/release/promise.js:649:10)
web        | [BE]     at Promise._settlePromises (/code/node_modules/bluebird/js/release/promise.js:729:18)
web        | [BE]     at _drainQueueStep (/code/node_modules/bluebird/js/release/async.js:93:12)
web        | [BE]     at _drainQueue (/code/node_modules/bluebird/js/release/async.js:86:9)
web        | [BE]     at Async._drainQueues (/code/node_modules/bluebird/js/release/async.js:102:5)
```

I commented out the `20220222145730-import-variant-data.ts` migration and I get this error now

**Comment by mozgzh** [comment]
I have a feeling there's an issue (maybe a race condition) where the migrations are running before all languages are imported. The original error regarding the migration is that `cy` (the Welsh locale) doesn't exist. The migration specifically queries for `cy` to retrieve it's `locale_id`which is causing the error (the locale_id is undefined). I'd imagine if Welsh was added to the DB manually, the migration would work as expected.

I think as a solution for now:

1. Delete/remove the migration `20220222145730-import-variant-data.ts` for now 
2. Import all sentences (this process takes a long time, modifying files while it runs may cause issues)
3. Exit out of the dev server
4. Change the `CV_IMPORT_SENTENCES` env variable to false
5. Add `20220222145730-import-variant-data.ts` back (simple if using `git restore`)
7. Start the server

I haven't tested the exact steps but would love for some feedback to see if it works. 

Long term solution is to simplify the startup logic, improve sentence import performance and reduce the chance of race condition/circular dependencies. Instead of using Pontoon as source of truth to get language data, it may make sense to populate the database via CLDR on start up, or create a migration that autopopulates the db with a preset languages.

**Comment by MichaelKohler** [comment]
> Instead of using Pontoon as source of truth to get language data, it may make sense to populate the database via CLDR on start up, or create a migration that autopopulates the db with a preset languages.

Generally not against that idea, but let's keep in mind that Sentence Collector takes the list from Pontoon. If the CV website shows other languages that are not contributeable on SC, it might be confusing. Happy to align on this when it comes to it :)

**Comment by moz-rotimib** [comment]
> I have a feeling there's an issue (maybe a race condition) where the migrations are running before all languages are imported. The original error regarding the migration is that `cy` (the Welsh locale) doesn't exist. The migration specifically queries for `cy` to retrieve it's `locale_id`which is causing the error (the locale_id is undefined). I'd imagine if Welsh was added to the DB manually, the migration would work as expected.
> 
> I think as a solution for now:
> 
>     1. Delete/remove the migration `20220222145730-import-variant-data.ts` for now
> 
>     2. Import all sentences (this process takes a long time, modifying files while it runs may cause issues)
> 
>     3. Exit out of the dev server
> 
>     4. Change the `CV_IMPORT_SENTENCES` env variable to false
> 
>     5. Add `20220222145730-import-variant-data.ts` back (simple if using `git restore`)
> 
>     6. Start the server
> 
> 
> I haven't tested the exact steps but would love for some feedback to see if it works.
> 
> Long term solution is to simplify the startup logic, improve sentence import performance and reduce the chance of race condition/circular dependencies. Instead of using Pontoon as source of truth to get language data, it may make sense to populate the database via CLDR on start up, or create a migration that autopopulates the db with a preset languages.

I've tried the steps and it seems the migration still fails even after all the sentences have been imported

**Comment by mozgzh** [comment]
@ftyers and @moz-rotimib can I get either/both of you to test the PR #3795 to see it fixes the above issues? Just pull it down locally, run on a fresh (or existing) setup and it should work. Confirm that the `locales` table is populated as expected (all columns are filled in, `name` column should have the ISO code of the language). And that `variants` table is populated with `cy` and `sw` variant information.

**Comment by moz-rotimib** [comment]
> @ftyers and @moz-rotimib can I get either/both of you to test the PR #3795 to see it fixes the above issues? Just pull it down locally, run on a fresh (or existing) setup and it should work. Confirm that the `locales` table is populated as expected (all columns are filled in, `name` column should have the ISO code of the language). And that `variants` table is populated with `cy` and `sw` variant information.

I'm testing locally now

**Comment by mozgzh** [comment]
#3795 has been merged, closing this ticket. if any other issues pop up related to migrations/startup, please create a new issue. Thanks again for everyones help! :rocket:
