### ISSUE TITLE
[BUG] multiple issues with docker local development

### ISSUE THREAD

**Issue by NiziL** [common-voice/common-voice#4708]
**Describe the bug**
Cannot start the app on a fresh clone

**To Reproduce**
1. Clone the repository
2. Follow the DEVELOPMENT.md tutorial

**Expected behavior**
Well... I expect it to start :clown_face: 

**Desktop or Mobile (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser: Firefox 133.0

**Additional context**
So, I've tried to start a local instance of `common-voice`, here is the issues I've been confronted to

- Permission error
  - a permission denied, solved by exporting `UID` and `GID` as specified in #4003 
- Authentication errors
  - a TypeError `Cannot read properties of null` (at [auth-router.ts](https://github.com/common-voice/common-voice/blob/main/server/src/auth-router.ts#L33)) if I don't set up the authentication, while the documentation tells me I could start the app without it
  - the doc is outdated, variables are no longer prefixed by `CV_AUTH0_`, but by `CV_FXA_`. I had to take a look at `server/src/config-helper.ts` to learn this
- DB Migration error
  - My `locales` table is not properly populated, there is only `en` and `unknown`. This leads to SQL errors `Column 'locale_id' cannot be null` on all `update-sentence-bands` files, as there is no `ady`, `kdb` and so on in the `locales` table.

Any help is greatly appreciated :)

**Comment by HarikalarKutusu** [comment]
I'm now trying `docker compose` workflow on Windows 11 through WSL2. My previous dev environment was fully on Windows/bare-metal. I had to solve lots of stuff wrt WSL of course.

> Permission error

I think #4801 solved it, at least in my case.

> Authentication errors

I spent a lot of time to understand why database tables are not created and there is no web server/page. I could only pass that stage when I commented out related line in ``server.ts, which of course caused further problems.

```
// app.use(await setupAuthRouter())
```
I've been using Auth0 in my old setup, but now I have to figure out how Mozilla Accounts work. It is definitely necessary to include that info in the `DEVELOPMENT.md` file.

@NiziL, if you can share your solution (even PR) it will help.

> DB Migration error

- After the comment out, the database tables could be created, migrations applied and my only locale (tr) could be imported. I had one deadlock error.

```
web  | [BE] error when inserting sentence batch from " Bin yıldır Allah'ın emri dendi kadınlara. " to "  ": Error: Deadlock found when trying to get lock; try restarting transaction
web  | [BE]     at PromisePool.query (/code/node_modules/mysql2/promise.js:356:22)
web  | [BE]     at PassThrough.<anonymous> (/code/server/src/lib/model/db/import-sentences.ts:105:24)
web  | [BE]     at PassThrough.emit (node:events:517:28)
web  | [BE]     at PassThrough.Readable.read (node:internal/streams/readable:582:10)
web  | [BE]     at flow (node:internal/streams/readable:1064:34)
web  | [BE]     at resume_ (node:internal/streams/readable:1045:3)
web  | [BE]     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
web  | [BE]   code: 'ER_LOCK_DEADLOCK',
web  | [BE]   errno: 1213,
...
```

- The `locales` table seems to be OK except "unknown" in the second record (345 locales).
- I did not encounter a migration error, `migrations` table seems to be OK.

There is no `20241112111800-update-sentence-bands.ts`, locales `ady` and `kbd` are in `2024110114510000-update-sentence-bands`

As we might see those sentence-band related migrations have different naming.
Normal naming: `20240916094400-add-dataset-19-0.ts`
Sentence-bands: `2024110114510000-update-sentence-bands.ts`

This causes a move to the 25th century (`24110114510000-update-sentence-bands`) , so they will be executed last. I think it is fine now:

![Image](https://github.com/user-attachments/assets/e19f49f3-4202-4560-a35b-fd31e76cbafc)

After getting over auth, I'll continue...

**Comment by NiziL** [comment]
@HarikalarKutusu I don't have my work laptop at the moment, so it's only from memory...

I've actually setup an Auth0 account/application as explained in `DEVELOPMENT.md`, your old  setup might still work.

But instead of having these variables in `.env-local-docker`:
```Dotenv
CV_AUTH0_DOMAIN="<domain_here>"
CV_AUTH0_CLIENT_ID="<client_id_here>"
CV_AUTH0_CLIENT_SECRET="<client_secret_here>"
```
I've put these one:
```Dotenv
CV_FXA_DOMAIN="<domain_here>"
CV_FXA_CLIENT_ID="<client_id_here>"
CV_FXA_CLIENT_SECRET="<client_secret_here>"
```

Don't know if it's the proper way of fixing it, but it did the trick for me.

> I did not encounter a migration error, migrations table seems to be OK.

I'll check it out on monday and keep you in touch :)

**Comment by HarikalarKutusu** [comment]
@NiziL, I wonder where did you register OpenID (for Mozilla for dev/testing purposes). The only plausible solution I can think of is to create my own local fake server using some open-source, too much hassle and lost resources just to try.

**Comment by NiziL** [comment]
@HarikalarKutusu Not sure if I fully understand the question... I've used [Auht0](https://auth0.com/) as an OpenID provider.

**Comment by HarikalarKutusu** [comment]
All is OK. I've got it working.
**A fix about FXA settings is required to the documentation as you mentioned of course...**
It took quite a while to import `en`, `de`, `tr` sentences. It forced the nVME drive where docker resides a lot thou, even with single core.

**Comment by moz-kathyreid** [comment]
Resolved via #4896 and #4897
